### ISSUE TITLE
两个字段拆分有问题

### ISSUE THREAD

**Issue by dingding2015** [brucexx/heisenberg#5]
按照文档配置两个字段拆分，测试的时候发现，拆分id加引号和不加引号的结果不一样，如果加引号，按照第一个拆分字段拆分，如果不加引号按照第二个拆分字段拆分。两个拆分字段均为int类型
mysql> explain insert into trans_tb(trans_id,uid) values(788,12809);
+-------------+------------------------------------------------------------+
| DATA_NODE   | SQL                                                        |
+-------------+------------------------------------------------------------+
| transDN[80] |  insert into trans_tb_80_9(trans_id,uid) values(788,12809) |
+-------------+------------------------------------------------------------+
1 row in set (0.02 sec)

mysql> explain insert into trans_tb(trans_id,uid) values('788','12809');
+-------------+----------------------------------------------------------------+
| DATA_NODE   | SQL                                                            |
+-------------+----------------------------------------------------------------+
| transDN[78] |  insert into trans_tb_78_8(trans_id,uid) values('788','12809') |
+-------------+----------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by brucexx** [comment]
是这样的，加引号是字符类型，不加引号是整型，这个要注意好

2015-03-20 14:55 GMT+08:00, dingding2015 <notifications@github.com>:

**Comment by dingding2015** [comment]
两个字段拆分怎么只按照其中的一个字段进行拆分了呢？不加引号，都是按照第一个拆分字段进行拆分的，没有同时按照两个字段进行拆分！

**Comment by dingding2015** [comment]
两个字段拆分的配置是当第一个字段不满足条件，按照第二个字段进行拆分，而不是同时按照两个字段进行拆分，
